version: '3.9'

services:
  web:
    build: .
    container_name: django_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - scheduler

  scheduler:
    build: .
    container_name: django_scheduler
    command: ["python", "manage.py", "runapscheduler"]
    volumes:
      - .:/app
