version: '3.9'
services:
  web:
    image: liuli01/django_huangping_project:latest
    container_name: huangping_web
    ports:
      - "8000:8000"
    environment:
      - APP_MODE=web
      - TZ=Asia/Shanghai
      - DEBUG=False
      - POSTGRES_DB=huangping
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=19921113ll
      - POSTGRES_HOST=10.0.151.90
      - POSTGRES_PORT=5432
    volumes:
      - app:/app
    depends_on:
      - scheduler

  scheduler:
    image: liuli01/django_huangping_project:latest
    container_name: huangping_scheduler
    environment:
      - APP_MODE=scheduler
      - TZ=Asia/Shanghai
      - DEBUG=False
      - POSTGRES_DB=huangping
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=19921113ll
      - POSTGRES_HOST=10.0.151.90
      - POSTGRES_PORT=5432
    volumes:
      - app:/app
volumes:
    app:
