# Generated by Django 5.2 on 2025-04-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FisrtModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linenos', models.BooleanField(auto_created=True, default=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fisrt_model',
                'managed': True,
            },
        ),
    ]
