# Generated by Django 5.2 on 2025-04-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_admin_app', '0003_alter_fisrtmodel_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisrtmodel',
            name='linenos',
            field=models.BooleanField(auto_created=True, default=False),
        ),
    ]
