# Generated by Django 5.2.3 on 2025-06-25 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_admin_app', '0004_alter_fisrtmodel_linenos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_key', models.CharField(max_length=50, unique=True)),
                ('method_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('remark', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CleanedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_key', models.CharField(max_length=10)),
                ('e_value', models.FloatField()),
                ('datetime', models.DateTimeField()),
                ('clean_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_admin_app.cleanmethod')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_admin_app.device')),
            ],
            options={
                'ordering': ['-datetime'],
                'indexes': [models.Index(fields=['device', 'clean_method', 'e_key', 'datetime'], name='rest_admin__device__31134b_idx')],
            },
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_key', models.CharField(max_length=10)),
                ('e_name', models.CharField(max_length=50)),
                ('e_num', models.CharField(max_length=20)),
                ('e_value', models.FloatField()),
                ('e_unit', models.CharField(max_length=20)),
                ('datetime', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_admin_app.device')),
            ],
            options={
                'ordering': ['-datetime'],
                'indexes': [models.Index(fields=['device', 'datetime'], name='rest_admin__device__2d7a9b_idx')],
            },
        ),
    ]
