# Generated by Django 5.2.3 on 2025-06-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_admin_app', '0005_cleanmethod_device_cleaneddata_rawdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisrtmodel',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='fisrtmodel',
            name='linenos',
            field=models.BooleanField(),
        ),
    ]
